# This source file is subject to the (Open Source Initiative) BSD license
# that is bundled with this package in the LICENSE file. It is also available
# through the world-wide-web at this URL: http://www.ontic.com.au/license.html
# If you did not receive a copy of the license and are unable to obtain it through
# the world-wide-web, please send an email to license@ontic.com.au immediately.
# Copyright (c) 2010-2016 Ontic. (http://www.ontic.com.au). All rights reserved.

---

- name: Redis | Configure working directory.
  become: yes
  file:
    path: '{{ redis_dir }}'
    owner: '{{ redis_user }}'
    group: '{{ redis_group }}'
    state: directory
    mode: 0755

- name: Redis | Configure pid directory.
  become: yes
  file:
    path: '{{ redis_pidfile | dirname }}'
    owner: '{{ redis_user }}'
    group: '{{ redis_group }}'
    state: directory
    mode: 0755
  when: redis_pidfile | default(None) != None

- name: Redis | Configure log directory.
  become: yes
  file:
    path: '{{ redis_logfile | dirname }}'
    owner: '{{ redis_user }}'
    group: '{{ redis_group }}'
    state: directory
    mode: 0755
  when: redis_logfile | default(None) != None

- name: Redis | Configure log file.
  become: yes
  file:
    path: '{{ redis_logfile }}'
    owner: '{{ redis_user }}'
    group: '{{ redis_group }}'
    state: touch
    mode: 0644
  when: redis_logfile | default(None) != None

- name: Redis | Redhat| Configure system init file.
  become: yes
  template:
    src: '{{ redis_sysconfig_init_template }}'
    dest: '/etc/sysconfig/redis_{{ redis_port }}'
    owner: root
    group: root
    mode: 0600
  notify: restart redis
  when: ansible_os_family == 'RedHat'

- name: Redis | Debian| Configure system init file.
  become: yes
  template:
    src: '{{ redis_sysconfig_init_template }}'
    dest: '/etc/default/redis_{{ redis_port }}'
    owner: root
    group: root
    mode: 0600
  notify: restart redis
  when: ansible_os_family == 'Debian'

- name: Redis | Configure Redis init file.
  become: yes
  template:
    src: '{{ redis_init_template }}'
    dest: '/etc/init.d/redis_{{ redis_port }}'
    owner: root
    group: root
    mode: 0755
  notify: restart redis

- name: Redis | Configure configuration file.
  become: yes
  template:
    src: '{{ redis_conf_template }}'
    dest: '/etc/redis/{{ redis_port }}.conf'
    owner: '{{ redis_user }}'
    group: '{{ redis_group }}'
    mode: 0644
  notify: restart redis

- name: Redis | Apply configuration changes.
  meta: flush_handlers