# This source file is subject to the (Open Source Initiative) BSD license
# that is bundled with this package in the LICENSE file. It is also available
# through the world-wide-web at this URL: http://www.ontic.com.au/license.html
# If you did not receive a copy of the license and are unable to obtain it through
# the world-wide-web, please send an email to license@ontic.com.au immediately.
# Copyright (c) 2010-2016 Ontic. (http://www.ontic.com.au). All rights reserved.

---

- name: Redis | Debian | Install dependencies.
  become: yes
  apt:
    pkg: '{{ item }}'
    update_cache: yes
    cache_valid_time: 86400
  with_items:
    - gcc
    - make
    - libc6-dev
  when: ansible_os_family == 'Debian'

- name: Redis | RedHat | Install dependencies.
  become: yes
  yum:
    name: '{{ item }}'
  with_items:
    - gcc
    - make
  when: ansible_os_family == 'RedHat'

- name: Redis | Retrieve system somaxconn setting.
  become: yes
  command: sysctl -n net.core.somaxconn
  register: sysctl_somaxconn
  changed_when: false

- name: Redis | Override system somaxconn setting.
  sysctl:
    name: net.core.somaxconn
    value: 5
    state: present
    reload: yes
    ignoreerrors: yes
  when: sysctl_somaxconn.stdout | int < redis_tcp_backlog

- name: Redis | Enable system overcommit memory.
  become: yes
  sysctl:
    name: vm.overcommit_memory
    value: 1
    state: present
    reload: yes
    ignoreerrors: yes

- name: Redis | Download source files.
  become: yes
  get_url:
    url: '{{ redis_download_url }}'
    dest: '/usr/local/src/redis-{{ redis_version }}.tar.gz'

- name: Redis | Extract source files.
  become: yes
  unarchive:
    src: '/usr/local/src/redis-{{ redis_version }}.tar.gz'
    dest: /usr/local/src
    creates: '/usr/local/src/redis-{{ redis_version }}/Makefile'
    copy: no

- name: Redis | Compile source files.
  become: yes
  command: 'make -j{{ ansible_processor_cores + 1 }}'
  args:
    chdir: '/usr/local/src/redis-{{ redis_version }}'
    creates: '/usr/local/src/redis-{{ redis_version }}/src/redis-server'

- name: Redis | Add user account.
  become: yes
  user:
    name: '{{ redis_user }}'
    group: '{{ redis_group }}'
    home: '{{ redis_install_dir }}'
    comment: Redis
    system: yes

- name: Redis | Create configuration directory.
  become: yes
  file:
    path: /etc/redis
    owner: root
    group: root
    state: directory
    mode: 0755

- name: Redis | Create installation directory.
  become: yes
  file:
    path: '{{ redis_install_dir }}'
    owner: '{{ redis_user }}'
    group: '{{ redis_group }}'
    state: directory
    mode: 0755

- name: Redis | Create runtime directory.
  become: yes
  file:
    path: /var/run/redis
    owner: '{{ redis_user }}'
    group: '{{ redis_group }}'
    state: directory

- name: Redis | Install source files.
  become: yes
  command: 'make PREFIX={{ redis_install_dir }} install'
  args:
    chdir: '/usr/local/src/redis-{{ redis_version }}'
    creates: '{{ redis_install_dir }}/bin/redis-server'